### ISSUE TITLE
TiFileHelper.GetTempFile no longer creates file (breaking behaviour)

### ISSUE THREAD

**Issue by MattWard-Ideagen** [appcelerator/titanium_mobile#12265] opened 2020-11-13 12:45 UTC
Issue
TiFileHelper.GetTempFile() no longer creates temporary file, only returns a file handle.   I think the culprit is https://github.com/appcelerator/titanium_mobile/commit/314b2bb7c71bfcacbfc044e21faa01f635f88b32 where result = File.createTempFile("tia", suffix, dir); was removed. I believe a result.createNewFile() after the file handle has been established in GetTempFile will restore behaviour.

Note:  TiFileHelper.getTempFileFromInputStream in the same class uses this function prior to v9.1.0 of titanium could expect the result of calling TiFileHelper.GetTempFile() to result in a temporary file to be created and return the file handle and is now currently broken on Android (the platform i'm testing on) as 'if (tempFile.exists())' returns false it won't populate the file with the contents.

**To Reproduce**
Steps to reproduce the behavior, e.g.:
1) tempFile =  TiFileHelper.GetTempFile() 
2) Verify Files.exists(tempFile.toPath(), LinkOption.NOFOLLOW_LINKS));

**Expected behavior**
Files.exists should return true to maintain previous behaviour.

**Environment**
Titanium SDK version: v9.2.1
CLI version: 8.1.1

**Logs**:
Not applicable.

(Attach by dragging into this issue)

**Comment by jquick-axway** [comment] 2020-11-19 03:11
I assume you're using the `TiFileHelper` Java class within your own module?

As of Titanium 9.3.0, I recommend that you do the below instead. The `getTiTempDir()` method was added to 9.3.0 and that entire directory tree will be auto-deleted on every app launch/exit via another thread... versus `TiFileHelper` blocks the UI thread when doing its deletes. The new approach is the superior solution. See PR #12161 for more details.
```java
File file = File.createTempFile("tifile", ".tmp", TiApplication.getInstance().getTiTempDir());
```

But I hear you. It no longer creates the file like it used to. The breaking-change was made on purpose as of Titanium 9.1.0 via PR #11490 . Internally, the thinking was that a getter method shouldn't create a file. Just like how our JavaScript `Ti.Filesystem.getFile()` method won't create a file either. That said, this change completely broke the Java `getTempFileFromInputStream()` method and that needs to be fixed.

**Comment by jquick-axway** [comment] 2020-11-19 03:18
I've confirmed that Titanium's JS [Ti.Media.previewImage()](https://docs.appcelerator.com/platform/latest/#!/api/Titanium.Media-method-previewImage) method fails to display blobs as of 9.1.0 due to this breaking-change. All of our other JS APIs appear to be fine. Nice catch. I'll write up a ticket for this.

**Comment by MattWard-Ideagen** [comment] 2020-11-19 08:16
Hi @jquick-axway, 
No we aren't using any of these directly in our code but via the third party bencoding.securely module (which I believe is quite widely used).   

This uses TiFileHelper.getTempFileFromInputStream,  however others may encounter the same issue meeting the deadline to upgrading modules/sdks to meet Apples deprecation of the UIWebView.   As you state its more optimal to not create file and fixing getTempFileFromInputStream would solve my problems,  so would be fine as noted breaking change?

**Comment by jquick-axway** [comment] 2020-11-23 20:26
@MattWard-Ideagen , the fix has been merged into "master" and "9_3_X". Thanks for bringing this up.

**Closed by jquick-axway** 2020-11-23 20:26 UTC
